import sys
import os
import pandas as pd
import numpy as np
from pysr import PySRRegressor
import warnings

# --- 0. 路径配置 ---
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(current_dir)
if project_root not in sys.path:
    sys.path.append(project_root)

from config import DATASET_PATH, PYSR_OUTPUT_DIR

warnings.filterwarnings("ignore", category=FutureWarning)
os.makedirs(PYSR_OUTPUT_DIR, exist_ok=True)
print(f"PySR 输出目录: '{PYSR_OUTPUT_DIR}'\n")

# --- 1. 数据加载与预处理 ---
try:
    df = pd.read_csv(DATASET_PATH)
except FileNotFoundError:
    print(f"错误: 找不到文件 at '{DATASET_PATH}'。")
    sys.exit()

df.replace({False: 0, True: 1}, inplace=True)

# --- 2. 准备特征和目标 ---
gamma_target_columns = [col for col in df.columns if col.startswith('yhat_')]
if not gamma_target_columns:
    print("错误: CSV中未找到 'yhat_' 开头的目标列。")
    sys.exit()

# [修改点] 确保删除 'timestamp' 而不是 'time'
columns_to_drop_for_X = gamma_target_columns + ['timestamp', 'regime']
existing_columns_to_drop = [col for col in columns_to_drop_for_X if col in df.columns]
X_df = df.drop(columns=existing_columns_to_drop, errors='ignore')
X_df = X_df.apply(pd.to_numeric, errors='coerce').fillna(0)
X = X_df.to_numpy()
feature_names = X_df.columns.to_list()

print(f"找到 {len(gamma_target_columns)} 个目标, {len(feature_names)} 个特征。")

# --- 3. 循环建模 ---
models = {}
for target_column in gamma_target_columns:
    print(f"\n{'='*60}\n正在分析: {target_column}\n{'='*60}")
    y = df[target_column].apply(pd.to_numeric, errors='coerce').fillna(0).to_numpy()
    
    model = PySRRegressor(
        niterations=40, 
        binary_operators=["+", "*", "/", "-"],
        unary_operators=["cos", "exp", "sin", "log"], 
        model_selection="best",
        # 保持临时文件整洁
        temp_equation_file=os.path.join(PYSR_OUTPUT_DIR, f"temp_hof_{target_column}.csv"),
        #verbosity=0 # 减少不必要的输出
    )
    model.fit(X, y)
    models[target_column] = model
    try:
        print(f"  -> 找到公式: {model.get_best()['equation']}")
    except (KeyError, IndexError):
        print("  -> 未找到有效公式。")

# --- 4. 生成包含安全措施的 Python 模块 ---
print("\n\n" + "#"*80)
print("分析完成！正在生成包含安全措施的 gamma_calculator.py...")
print("#"*80)

# [修改点 1] 在生成的代码中注入安全函数
python_code_lines = [
    "# This file is auto-generated by PySR. Do not edit it manually.",
    "import numpy as np", 
    "import torch",
    "import sys",
    "import os",
    "",
    "# --- 安全函数，防止数学错误 ---",
    "def safe_log(x):",
    "    # 防止对 0 或负数取对数",
    "    return np.log(np.abs(x) + 1e-9)",
    "",
    "# --- 动态路径，导入全局配置 ---",
    "current_dir = os.path.dirname(os.path.abspath(__file__))",
    "project_root = os.path.dirname(os.path.dirname(current_dir))",
    "if project_root not in sys.path:",
    "    sys.path.append(project_root)",
    "try:",
    "    from config import DEVICE",
    "except ImportError:",
    "    DEVICE = torch.device('cpu')",
    "",
    "class GeneratedGammaCalculator:",
    "    def __init__(self):", 
    "        np.seterr(all='ignore') # 忽略所有numpy计算警告",
    f"        self.feature_names = {feature_names!r}",
    f"        self.gamma_signals = {gamma_target_columns!r}\n",
    "    def compute(self, state):",
]

# 状态解包
python_code_lines.append("        # Unpack state variables")
for i, name in enumerate(feature_names):
    python_code_lines.append(f"        x{i} = state[{i}]") 
python_code_lines.append("\n        # Calculate gamma components")

# 遍历模型生成公式
gamma_component_vars = []
for i, target_column in enumerate(gamma_target_columns):
    fitted_model = models.get(target_column)
    component_var_name = f"gamma_{i}"
    gamma_component_vars.append(component_var_name)

    try:
        equation_str = fitted_model.get_best()["equation"]
        # [修改点 2] 将 log() 替换为我们定义的 safe_log()
        py_equation = equation_str.replace('sin(', 'np.sin(')\
                                  .replace('cos(', 'np.cos(')\
                                  .replace('exp(', 'np.exp(')\
                                  .replace('log(', 'safe_log(')
        python_code_lines.append(f"        {component_var_name} = {py_equation}")
    except (KeyError, IndexError):
        python_code_lines.append(f"        {component_var_name} = 0.0  # Fallback for {target_column}")

# [修改点 3] 增加最终的数值清洗步骤
python_code_lines.extend([
    "\n        # Combine components into a list",
    f"        gamma_values = [{', '.join(gamma_component_vars)}]",
    "",
    "        # [CRITICAL] 清洗 NaN 和 Inf 值，替换为0，确保 SAC 不会崩溃",
    "        gamma_array = np.array(gamma_values, dtype=np.float32)",
    "        gamma_array = np.nan_to_num(gamma_array, nan=0.0, posinf=0.0, neginf=0.0)",
    "",
    "        # 转换为 PyTorch tensor 并返回",
    "        return torch.from_numpy(gamma_array).to(DEVICE).unsqueeze(0)"
])

py_file_path = os.path.join(PYSR_OUTPUT_DIR, "gamma_calculator.py")
try:
    with open(py_file_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(python_code_lines))
    print(f"\n✅ 安全版 Python 模块已写入: {py_file_path}")
except Exception as e:
    print(f"\n❌ 写入 gamma_calculator.py 失败: {e}")

print("\n分析全部完成！")