# This file is auto-generated by PySR. Do not edit it manually.
import numpy as np
import torch
import sys
import os

# --- 安全函数，防止数学错误 ---
def safe_log(x):
    # 防止对 0 或负数取对数
    return np.log(np.abs(x) + 1e-9)

# --- 动态路径，导入全局配置 ---
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(os.path.dirname(current_dir))
if project_root not in sys.path:
    sys.path.append(project_root)
try:
    from config import DEVICE
except ImportError:
    DEVICE = torch.device('cpu')

class GeneratedGammaCalculator:
    def __init__(self):
        np.seterr(all='ignore') # 忽略所有numpy计算警告
        self.feature_names = ['temperature', 'wind_speed', 'solar_irradiance', 'precipitation_mm', 'elec_vmin', 'elec_vmax', 'elec_vavg', 'elec_line_loading_max', 'elec_line_loading_top1', 'elec_line_loading_top2', 'elec_line_loading_top3', 'elec_vmax_nonslack', 'elec_line_i_ka_max', 'elec_p_loss_mw', 'elec_soc_1', 'elec_soc_2', 'elec_soc_3', 'elec_soc_4', 'elec_soc_5', 'elec_any_violate', 'elec_violate_v', 'elec_violate_line', 'grid_load_demand', 'hour_of_day', 'day_of_week']
        self.gamma_signals = ['yhat_ess1_up', 'yhat_ess1_down', 'yhat_ess2_up', 'yhat_ess2_down', 'yhat_ess3_up', 'yhat_ess3_down', 'yhat_ess4_up', 'yhat_ess4_down', 'yhat_ess5_up', 'yhat_ess5_down', 'yhat_sop1_fwd', 'yhat_sop1_rev', 'yhat_sop2_fwd', 'yhat_sop2_rev', 'yhat_pv1', 'yhat_pv2', 'yhat_pv3', 'yhat_pv4', 'yhat_pv5', 'yhat_pv6', 'yhat_wt1', 'yhat_wt2', 'yhat_wt3', 'yhat_wt4', 'yhat_wt5', 'yhat_wt6']

    def compute(self, state):
        # Unpack state variables
        x0 = state[0]
        x1 = state[1]
        x2 = state[2]
        x3 = state[3]
        x4 = state[4]
        x5 = state[5]
        x6 = state[6]
        x7 = state[7]
        x8 = state[8]
        x9 = state[9]
        x10 = state[10]
        x11 = state[11]
        x12 = state[12]
        x13 = state[13]
        x14 = state[14]
        x15 = state[15]
        x16 = state[16]
        x17 = state[17]
        x18 = state[18]
        x19 = state[19]
        x20 = state[20]
        x21 = state[21]
        x22 = state[22]
        x23 = state[23]
        x24 = state[24]

        # Calculate gamma components
        gamma_0 = x19
        gamma_1 = x20 + ((x19 * (np.cos(np.sin(x8 - np.cos(x8))) + (np.cos(x8) + -0.41160122))) / (((-1.5241412 + (x23 / np.cos(x1 - -2.2420778))) * -415.21283) + 0.9300668))
        gamma_2 = (np.cos(x9 + -1.4177023) / (((((x2 + -0.65151423) + (x17 / x8)) + x20) / -0.0023544154) + 0.9539104)) + x20
        gamma_3 = np.sin((x20 * np.cos(-1.3750819 / ((x7 + (x2 / (np.exp(np.exp(np.sin(x23))) + (x2 / np.exp(x15 - x10))))) / np.exp(x15 - x10)))) * 1.7288122)
        gamma_4 = x19 - ((np.cos(x8 * -0.24597403) * -0.016637705) * np.exp((((np.cos(x2) + (x19 * -62.7554)) + np.sin(x9 / 0.95359635)) / 0.5006268) / x5))
        gamma_5 = np.sin(x19 * np.exp(np.exp(np.sin(-8.553728 - np.sin(np.exp(6.4109454 - safe_log(np.cos(x9 + -1.3015349) + x10)))))))
        gamma_6 = np.sin(np.cos(np.sin((np.exp(x4) / ((x12 / -1.5602541) - 0.23596108)) + np.cos(np.sin(x20 + (np.exp(x6) / ((x12 / -1.0553254) - 0.19232064))) * 1.7510455)) * -2.1311216) + 0.45967367)
        gamma_7 = np.sin(np.sin(x20) - np.sin(x20 / np.sin(-0.7883127 / (x13 + 0.08758952))))
        gamma_8 = (0.0012726008 / np.cos(((x4 + x18) / ((x18 * -0.0004971749) / np.cos(np.cos(x19)))) * -0.62270546)) + x19
        gamma_9 = x20 * np.cos(np.sin(x0) / (x23 + -1.999649))
        gamma_10 = np.sin(safe_log(x9) * (safe_log(x5) + (x20 * 2.9925225)))
        gamma_11 = np.cos((np.cos((-1.4983665 - x17) * (x4 * 1.3068718)) + x21) + -0.6159319)
        gamma_12 = x20 * np.sin(np.cos(2.3273084 / x13) + 2.1519413)
        gamma_13 = np.cos(np.sin(x4 * x18))
        gamma_14 = x19
        gamma_15 = x20 * 1.0
        gamma_16 = x20
        gamma_17 = x20
        gamma_18 = x20
        gamma_19 = (0.011382344 / (0.60781425 - x13)) + x20
        gamma_20 = x20
        gamma_21 = x19
        gamma_22 = x20 * x20
        gamma_23 = x19
        gamma_24 = x20
        gamma_25 = x19

        # Combine components into a list
        gamma_values = [gamma_0, gamma_1, gamma_2, gamma_3, gamma_4, gamma_5, gamma_6, gamma_7, gamma_8, gamma_9, gamma_10, gamma_11, gamma_12, gamma_13, gamma_14, gamma_15, gamma_16, gamma_17, gamma_18, gamma_19, gamma_20, gamma_21, gamma_22, gamma_23, gamma_24, gamma_25]

        # [CRITICAL] 清洗 NaN 和 Inf 值，替换为0，确保 SAC 不会崩溃
        gamma_array = np.array(gamma_values, dtype=np.float32)
        gamma_array = np.nan_to_num(gamma_array, nan=0.0, posinf=0.0, neginf=0.0)

        # 转换为 PyTorch tensor 并返回
        return torch.from_numpy(gamma_array).to(DEVICE).unsqueeze(0)