# This file is auto-generated by PySR.
import numpy as np
import torch
import sys
import os

# --- Math Safety Functions ---
def safe_sqrt(x): return np.sqrt(np.abs(x))
def safe_div(a, b): return np.divide(a, b + 1e-9)
def safe_log(x): return np.log(np.abs(x) + 1e-9)
def cube(x): return np.power(x, 3)

# --- Path Configuration ---
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(os.path.dirname(current_dir))
if project_root not in sys.path: sys.path.append(project_root)
try: from config import DEVICE
except ImportError: DEVICE = torch.device('cpu')

class GeneratedGammaCalculator:
    def __init__(self):
        np.seterr(all='ignore')
        self.feature_names = ['temperature', 'wind_speed', 'solar_irradiance', 'precipitation_mm', 'elec_vmin', 'elec_vmax', 'elec_vavg', 'elec_line_loading_max', 'elec_line_loading_top1', 'elec_line_loading_top2', 'elec_line_loading_top3', 'elec_vmax_nonslack', 'elec_line_i_ka_max', 'elec_p_loss_mw', 'elec_soc_1', 'elec_soc_2', 'elec_soc_3', 'elec_soc_4', 'elec_soc_5', 'grid_load_demand', 'hour_of_day', 'day_of_week']
        self.gamma_signals = ['sens_action_batt_0', 'sens_action_batt_1', 'sens_action_batt_2', 'sens_action_batt_3', 'sens_action_batt_4']

    def compute(self, state):
        # Unpack features based on training configuration
        x0 = state[0] # temperature
        x1 = state[1] # wind_speed
        x2 = state[2] # solar_irradiance
        x3 = state[3] # precipitation_mm
        x4 = state[4] # elec_vmin
        x5 = state[5] # elec_vmax
        x6 = state[6] # elec_vavg
        x7 = state[7] # elec_line_loading_max
        x8 = state[8] # elec_line_loading_top1
        x9 = state[9] # elec_line_loading_top2
        x10 = state[10] # elec_line_loading_top3
        x11 = state[11] # elec_vmax_nonslack
        x12 = state[12] # elec_line_i_ka_max
        x13 = state[13] # elec_p_loss_mw
        x14 = state[14] # elec_soc_1
        x15 = state[15] # elec_soc_2
        x16 = state[16] # elec_soc_3
        x17 = state[17] # elec_soc_4
        x18 = state[18] # elec_soc_5
        x19 = state[19] # grid_load_demand
        x20 = state[20] # hour_of_day
        x21 = state[21] # day_of_week

        # Formulas
        gamma_0 = np.square(-0.00023640059 / ((((x20 + x3) - 0.4161585) + -0.39995426) + (x3 - x13)))
        gamma_1 = cube(x0 / x19) * 83.01992
        gamma_2 = x20 / (x13 + (np.square(x20) + cube(x1 * (x3 + x13))))
        gamma_3 = 1.7857401 / (x1 + (x20 - -1.9209685))
        gamma_4 = (2.2903242 / np.square(x13 * ((x7 / 1.5671674) - x15))) / cube(x7)

        # Output Assembly
        gamma_values = [gamma_0, gamma_1, gamma_2, gamma_3, gamma_4]
        # 数值清洗: 替换 NaN/Inf 为 0
        gamma_array = np.nan_to_num(np.array(gamma_values, dtype=np.float32), nan=0.0, posinf=0.0, neginf=0.0)
        return torch.from_numpy(gamma_array).to(DEVICE).unsqueeze(0)